### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by sakatosi0728** [sakatosi0728/furima_28374#9]
URL : 
https://furima-28374.herokuapp.com/

Basic認証のIDとパスワード:
admin / 1111

出品者用のメールアドレスとパスワード:
seller@seller.com / seller

購入者用のメールアドレスとパスワード:
buyer1@buyer.com / buyer1

購入用カードの番号・期限・セキュリティコード:
4242424242424242 ・ 1/23 ・ 123

**Comment by sho0127** [comment]
阪井さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
「誤ったクレジットカード情報を入力後、購入ボタンを押すとエラーメッセージが表示された。（こちらは問題ない）
しかし、その後トップページに移動するとその商品がsoldoutになっていた」
修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by sakatosi0728** [comment]
修正しましたので再度、確認をお願いします。

URL :
https://furima-28374.herokuapp.com/

Basic認証のIDとパスワード:
admin / 1111

出品者用のメールアドレスとパスワード:
seller@seller.com / seller

購入者用のメールアドレスとパスワード:
buyer1@buyer.com / buyer1

購入用カードの番号・期限・セキュリティコード:
4242424242424242 ・ 1/23 ・ 123

**Comment by sho0127** [comment]
阪井さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
「カード情報を全てコピペして必須項目を埋めて購入を実行しようとしても購入ができない」
こちら阪井さんの方でも今一度購入者アカウントでお試し頂ければと思います。
修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by sakatosi0728** [comment]
再度修正いたしましたので、ご確認お願い致します。

URL :
https://furima-28374.herokuapp.com/

Basic認証のIDとパスワード:
admin / 1111

出品者用のメールアドレスとパスワード:
seller@seller.com / seller

購入者用のメールアドレスとパスワード:
buyer1@buyer.com / buyer1

購入用カードの番号・期限・セキュリティコード:
4242424242424242 ・ 1/23 ・ 123

**Comment by sho0127** [comment]
阪井さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
